[dependencies]

[package]
  cjc-version = "1.0.0"
  compile-option = ""
  description = "A DNS message parsing and processing library implemented in Cangjie"
  link-option = ""
  name = "dnsmsg"
  output-type = "static"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
